---
name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        jdk: [8, 11, 17, 20]

    name: Java ${{ matrix.jdk }}

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java ${{ matrix.jdk }}
        uses: actions/setup-java@v3.11.0
        with:
          distribution: temurin
          java-version: ${{ matrix.jdk }}
          cache: maven
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@master
        with:
          lein: latest
      - name: Run tests
        run: lein do clean, all midje, all check
